default: &DEFAULT
  num_epochs: 20
  batch_size: 64
  
UNet_LM_CL:
  <<: *DEFAULT
  model_name: UNet
  image_dir: "imgs"
  target_dir: "heatmaps"
  target_sfx: ".npy"
  checkpoint_dir: "Checkpoints/Test1"
  log_dir: 'Logs/Test1'
  dataset_class: "SpineDataset"
  loss: "custom_weighted_loss"
  eval_metric: "pb_mse_metric"
  num_classes: 13
  batch_size: 16
  input_size: 256
  early_stopping_up: False
  
